<?php /* Smarty version 2.6.18, created on 2016-07-20 18:37:01
         compiled from public/hello_box.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('block', 'nocache', 'public/hello_box.tpl', 1, false),)), $this); ?>
<?php $this->_cache_serials['./runtime/comps/default/space_php/\%%80^80F^80F74A24%%hello_box.tpl.inc'] = '2ca6b18ccec1d9e2ad9e187726b002ae'; ?><div id="hello" class="send">	<div class="column" style="width:450px;">		<div class="column_title">打个招呼</div>		<div class="column_content">			<form action="<?php echo $this->_tpl_vars['app']; ?>
/sms/sendhello/uid/<?php if ($this->caching && !$this->_cache_including): echo '{nocache:2ca6b18ccec1d9e2ad9e187726b002ae#0}'; endif;$this->_tag_stack[] = array('nocache', array()); $_block_repeat=true;smarty_block_nocache($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php if ($_SESSION['user_info']['id']): ?><?php echo $_SESSION['user_info']['id']; ?>
<?php else: ?><?php echo $_GET['uid']; ?>
<?php endif; ?><?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_nocache($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); if ($this->caching && !$this->_cache_including): echo '{/nocache:2ca6b18ccec1d9e2ad9e187726b002ae#0}'; endif;?>" method="post">				<input type="hidden" id="hello_id" name="dst_id"  />				<input type="hidden" name="src_id" value="<?php if ($this->caching && !$this->_cache_including): echo '{nocache:2ca6b18ccec1d9e2ad9e187726b002ae#1}'; endif;$this->_tag_stack[] = array('nocache', array()); $_block_repeat=true;smarty_block_nocache($this->_tag_stack[count($this->_tag_stack)-1][1], null, $this, $_block_repeat);while ($_block_repeat) { ob_start(); ?><?php echo $_SESSION['user_info']['id']; ?>
<?php $_block_content = ob_get_contents(); ob_end_clean(); $_block_repeat=false;echo smarty_block_nocache($this->_tag_stack[count($this->_tag_stack)-1][1], $_block_content, $this, $_block_repeat); }  array_pop($this->_tag_stack); if ($this->caching && !$this->_cache_including): echo '{/nocache:2ca6b18ccec1d9e2ad9e187726b002ae#1}'; endif;?>" />				<table class="hello">				<tr>					<td colspan="4">我要对 <span id="hello_name" style="font-weight:bold;color:green">admin</span> 打招呼:</td>				</tr>				<tr>					<td><input type="radio" name="hello_type" value="1" checked> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/wx.gif" /> 微笑</td>					<td><input type="radio" name="hello_type" value="2"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/cyx.gif" /> 踩一下</td>					<td><input type="radio" name="hello_type" value="3"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/wgs.gif" /> 握个手</td>					<td><input type="radio" name="hello_type" value="4"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/jy.gif" /> 加油</td>				</tr>				<tr>					<td><input type="radio" name="hello_type" value="5"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/pmy.gif" /> 抛媚眼</td>					<td><input type="radio" name="hello_type" value="6"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/yb.gif" /> 拥抱</td>					<td><input type="radio" name="hello_type" value="7"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/fw.gif" /> 飞吻</td>					<td><input type="radio" name="hello_type" value="8"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/nyy.gif" /> 挠痒痒</td>				</tr>				<tr>					<td><input type="radio" name="hello_type" value="9"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/gyq.gif" /> 给一拳</td>					<td><input type="radio" name="hello_type" value="10"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/dyx.gif" /> 电一下</td>					<td><input type="radio" name="hello_type" value="11"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/yw.gif" /> 依偎</td>					<td><input type="radio" name="hello_type" value="12"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/ppjb.gif" /> 拍拍肩膀</td>				</tr>				<tr>					<td><input type="radio" name="hello_type" value="13"> <img src="<?php echo $this->_tpl_vars['public']; ?>
/images/hello/yyk.gif" /> 咬一口</td><td></td><td></td><td></td>				</tr>				<tr height="50px">					<td style="text-align:left">我要大声对Ta说:</td>					<td colspan="3" align="left"><input type="text" name="content" style="border:1px solid #cccccc;width:95%" /></td>				</tr>				<tr>					<td colspan="4" style="text-align:right"><input type="submit" value="发送" /></td>				</tr>				</table>				</form>			</div>		</div>		<div class="close"><a href="javascript:void(0);" onclick="show('hello','none');show('bottom','none');"></a></div>	</div><script type="text/javascript">	function getname(id){		document.getElementById("hello_name").innerHTML=document.getElementById("send_name_"+id).childNodes[0].nodeValue;		document.getElementById("hello_id").value=document.getElementById("send_uid_"+id).childNodes[0].nodeValue;	}</script>